server:
  port: 8080
  servlet:
    context-path: /grabtutor

spring:
  application:
    name: grabtutor
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:khoatrancraft3@gmail.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  datasource:
    url: jdbc:mysql://localhost:3306/grabtutor_db
    username: root
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # tự động cập nhật CSDL khi entity thay đổi
    show-sql: true        # in câu SQL ra console
    properties:
      hibernate:
        format_sql: true  # format SQL cho dễ đọc

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


jwt:
  signer-key: "Qk9WeWZxa0xEaEpUdWxzRk1sR1h5ZWlMV0RuY3NaRktyZ0tLY3VzaEZtQnhJckN1a2MzS1A3UjA9"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds


cloudinary:
  cloud_name: dk3pmg0tr
  api_key: 746891315239322
  api_secret: ${CLOUDINARY_API_SECRET:bRSqau7RN7Ji8TUo_nYilGk7pK0}


