server:
  port: 8080
  servlet:
    context-path: /grabtutor

spring:
  application:
    name: grabtutor

  datasource:
    url: jdbc:mysql://localhost:3306/grabtutor_db
    username: root
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # tự động cập nhật CSDL khi entity thay đổi
    show-sql: true        # in câu SQL ra console
    properties:
      hibernate:
        format_sql: true  # format SQL cho dễ đọc
jwt:
  signerKey: "Qk9WeWZxa0xEaEpUdWxzRk1sR1h5ZWlMV0RuY3NaRktyZ0tLY3VzaEZtQnhJckN1a2MzS1A3UjA9"
  validDuration: 3600 # in second
  refreshableDuration: 36000 # in seconds