spring:
  application:
    name: grabtutor

    datasource:
      url: jdbc:mysql://localhost:3306/grabtutor_db
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver